## Python/Jupyter 10 Minute Crash Course 
Jupyter notebooks let you combine code, plots and notes - similar to 
R markdown. They can run and combine Julia, Python and R (Ju Pyt [e] R),
and some other languages.

This is a markdown cell where you can put comments, notes, etc

In [1]:
# This is a code cell

### Variables

In [25]:
my_variable = "some data"
my_variable

'some data'

### Basic Python data types 

Integers

In [27]:
a = 1
a

1

In [29]:
a + 1

2

Floats

In [9]:
b = 0.1
b

0.1

In [11]:
b + a

0.2

Strings

In [16]:
a = "a string"
a

'a string'

In [19]:
"I am " + a

'I am a string'

Lists

In [34]:
# Making a list
l = [1, 2, 3, "x", a]
l

[1, 2, 3, 'x', 1]

In [21]:
# Indexing a list
l[0]

1

In [22]:
# Indexing a range
l[0:3]

[1, 2, 3]

Dictionaries

In [45]:
my_dict = {"apples": "oranges"}
my_dict["apples"]

'oranges'

### Functions and methods

In [30]:
type(l)

list

In [41]:
sum([1, 2, 3])

6

In [35]:
l.append("y")
l

[1, 2, 3, 'x', 1, 'y']

### For loops

In [54]:
# Iterate over the items in our list
for item in l:
    # Do something
    print(item, type(item))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
x <class 'str'>
1 <class 'int'>
y <class 'str'>


### Import extra modules

In [38]:
import math

math.sqrt(9)

3.0

In [39]:
from math import sqrt

sqrt(9)

3.0

In [40]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

### A primer on vectors

In [48]:
import numpy as np

vect = np.zeros(10, dtype=np.int64)
vect

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
vect[0] = 1
vect

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
vect[0] = "a"

ValueError: invalid literal for int() with base 10: 'a'

In [53]:
vect + 1

array([2, 1, 1, 1, 1, 1, 1, 1, 1, 1])